=head1 SYNOPSIS

Linux::Inotify2::Recur is experiment code extending Linux::Inotify2 to recursive 
watch some directories. Also add, remove and change wachts as needed.

=head1 Debugging

To run inot in debug mode try

    cd perl-inotify
    mkdir ./test-dir
    perl inot.pl 0 8

and then do some changes inside ./test-dir.
See also ./docs/sample-output.txt

=head1 See also

L<Linux::Inotify2|Linux::Inotify2> CPAN module.

=head1 Author

Michal Jurosz - L<irc://irc.freenode.org/#mj41> - email: mj{$zav}mj41.cz
