=head1 SYNOPSIS

Linux::Inotify2 experiment code. Trying recursive watch some directories.
Also add, remove and change wachts as needed.

=head1 Debugging

To run inot in debug mode try
    cd perl-inotify
    mkdir ./test-dir
    perl inot.pl 0 10
and then do some changes inside ./test-dir.

=head1 Troubleshooting

=head2 Error "no space left on device" ===

See L<Kernel Korner - Intro to inotify|http://www.linuxjournal.com/article/8478?page=0,3>, Sep 28 2005, Robert Love, Linux Journal
Commands like
    cat /proc/sys/fs/inotify/max_queued_events
    cat /proc/sys/fs/inotify/max_user_watches

    echo 65536 > /proc/sys/fs/inotify/max_queued_events
    echo 32768 > /proc/sys/fs/inotify/max_user_watches
should help.

=head1 See also

L<Linux::Inotify2>
